package com.zmcsoft.apsp.client.sdk.drivers.multiple;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : drivers\identity\mtx_32.h:6</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class MagCard extends Structure {
	public byte track1_len;
	public byte track2_len;
	public byte track3_len;
	/** C type : unsigned char[80] */
	public byte[] track1_data = new byte[80];
	/** C type : unsigned char[41] */
	public byte[] track2_data = new byte[41];
	/** C type : unsigned char[170] */
	public byte[] track3_data = new byte[170];
	public MagCard() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("track1_len", "track2_len", "track3_len", "track1_data", "track2_data", "track3_data");
	}
	/**
	 * @param track1_data C type : unsigned char[80]<br>
	 * @param track2_data C type : unsigned char[41]<br>
	 * @param track3_data C type : unsigned char[170]
	 */
	public MagCard(byte track1_len, byte track2_len, byte track3_len, byte track1_data[], byte track2_data[], byte track3_data[]) {
		super();
		this.track1_len = track1_len;
		this.track2_len = track2_len;
		this.track3_len = track3_len;
		if ((track1_data.length != this.track1_data.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.track1_data = track1_data;
		if ((track2_data.length != this.track2_data.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.track2_data = track2_data;
		if ((track3_data.length != this.track3_data.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.track3_data = track3_data;
	}
	public MagCard(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MagCard implements Structure.ByReference {
		
	};
	public static class ByValue extends MagCard implements Structure.ByValue {

	};
}
