package com.zmcsoft.apsp.client;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.win32.StdCallLibrary;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>K2616_Dll</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface K2616_DllLibrary extends StdCallLibrary {
	public static final String JNA_LIBRARY_NAME = "card/K2616_Dll";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(K2616_DllLibrary.JNA_LIBRARY_NAME);
	public static final K2616_DllLibrary INSTANCE = (K2616_DllLibrary)Native.loadLibrary(K2616_DllLibrary.JNA_LIBRARY_NAME, K2616_DllLibrary.class);

	 static void main(String[] args) {

	}
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Bad_CommOpen = (int)-101;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Bad_CommSet = (int)-102;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Bad_CommTimeouts = (int)-999;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Bad_CommQueue = (int)-998;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Bad_CommClose = (int)-105;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Bad_SendByte = (int)-106;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Bad_SendData_Len = (int)-107;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Bad_ReceiveData_ReadFile = (int)-103;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Bad_ReceiveData_Len = (int)-104;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Bad_Parameter = (int)-200;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int CardBoxEmpty = (int)0xA0;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int CardJam = (int)0xA2;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int RecycleBoxFull = (int)0xA1;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int RecycleBoxNotInPosition = (int)0xA3;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int CardBoxNotInPosition = (int)0xA4;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int HookMoveBox1NotEmpty = (int)0xA7;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int HookMoveTimeOut = (int)0xA8;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int MoverMoveError = (int)0xAE;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int PlatformWaitCard = (int)0xAF;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int PlatformFlipCard = (int)0xB0;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Hook1MoveFail = (int)0xB1;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int Hook2MoveFail = (int)0xB2;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int CardIsInPlatform = (int)0xB3;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int SendCardToPlatformFail = (int)0xB4;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int CardIsNotInPlatform = (int)0xB5;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int SendCardFailed = (int)0xC6;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int RecyclePlatformCard = (int)0xC7;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int RecycleCardFailed = (int)0xC8;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int HaveCardAndSendCardFailed = (int)0xC9;
	/** <i>native declaration : drivers\card\K2616_Dll.h</i> */
	public static final int HaveNoCardRecycleCardFailed = (int)0xCA;
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>HANDLE K2616_CommOpen(char*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:49</i><br>
	 * @deprecated use the safer methods {@link #K2616_CommOpen(ByteBuffer)} and {@link #K2616_CommOpen(Pointer)} instead
	 */
	@Deprecated 
	HANDLE K2616_CommOpen(Pointer Port);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>HANDLE K2616_CommOpen(char*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:49</i>
	 */
	HANDLE K2616_CommOpen(ByteBuffer Port);
	/**
	 * Original signature : <code>HANDLE K2616_CommOpenWithBaud(char*, unsigned int)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:50</i><br>
	 * @deprecated use the safer methods {@link #K2616_CommOpenWithBaud(ByteBuffer, int)} and {@link #K2616_CommOpenWithBaud(Pointer, int)} instead
	 */
	@Deprecated 
	HANDLE K2616_CommOpenWithBaud(Pointer Port, int _data);
	/**
	 * Original signature : <code>HANDLE K2616_CommOpenWithBaud(char*, unsigned int)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:50</i>
	 */
	HANDLE K2616_CommOpenWithBaud(ByteBuffer Port, int _data);
	/**
	 * Original signature : <code>int K2616_CommClose(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:51</i>
	 */
	int K2616_CommClose(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_GetSysVerion(HANDLE, char*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:52</i><br>
	 * @deprecated use the safer methods {@link #K2616_GetSysVerion(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_GetSysVerion(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_GetSysVerion(HANDLE ComHandle, Pointer strVerion);
	/**
	 * Original signature : <code>int K2616_GetSysVerion(HANDLE, char*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:52</i>
	 */
	int K2616_GetSysVerion(HANDLE ComHandle, ByteBuffer strVerion);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_SetCommBaud(HANDLE, unsigned int)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:54</i>
	 */
	int K2616_SetCommBaud(HANDLE ComHandle, int _Baud);
	/**
	 * Original signature : <code>int K2616_Reset(HANDLE, BYTE, BYTE[50])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:55</i><br>
	 * @deprecated use the safer methods {@link #K2616_Reset(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_Reset(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_Reset(HANDLE ComHandle, byte _PM, Pointer _VerCode);
	/**
	 * Original signature : <code>int K2616_Reset(HANDLE, BYTE, BYTE[50])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:55</i>
	 */
	int K2616_Reset(HANDLE ComHandle, byte _PM, ByteBuffer _VerCode);
	/**
	 * Original signature : <code>int K2616_CheckCardPosition(HANDLE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:56</i><br>
	 * @deprecated use the safer methods {@link #K2616_CheckCardPosition(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_CheckCardPosition(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_CheckCardPosition(HANDLE ComHandle, Pointer _Position);
	/**
	 * Original signature : <code>int K2616_CheckCardPosition(HANDLE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:56</i>
	 */
	int K2616_CheckCardPosition(HANDLE ComHandle, ByteBuffer _Position);
	/**
	 * Original signature : <code>int K2616_CheckSensorStates(HANDLE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:57</i><br>
	 * @deprecated use the safer methods {@link #K2616_CheckSensorStates(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_CheckSensorStates(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_CheckSensorStates(HANDLE ComHandle, Pointer _States);
	/**
	 * Original signature : <code>int K2616_CheckSensorStates(HANDLE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:57</i>
	 */
	int K2616_CheckSensorStates(HANDLE ComHandle, ByteBuffer _States);
	/**
	 * Original signature : <code>int K2616_CheckSensorVoltage(HANDLE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:58</i><br>
	 * @deprecated use the safer methods {@link #K2616_CheckSensorVoltage(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_CheckSensorVoltage(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_CheckSensorVoltage(HANDLE ComHandle, Pointer _Valtage);
	/**
	 * Original signature : <code>int K2616_CheckSensorVoltage(HANDLE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:58</i>
	 */
	int K2616_CheckSensorVoltage(HANDLE ComHandle, ByteBuffer _Valtage);
	/**
	 * Original signature : <code>int K2616_EnterCard(HANDLE, BYTE, DWORD)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:59</i>
	 */
	int K2616_EnterCard(HANDLE ComHandle, byte EnterType, int WaitTime);
	/**
	 * ;;;\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int K2616_EnterCardUntime(HANDLE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:60</i>
	 */
	int K2616_EnterCardUntime(HANDLE ComHandle, byte EnterType);
	/**
	 * Original signature : <code>int K2616_MoveCard(HANDLE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:61</i>
	 */
	int K2616_MoveCard(HANDLE ComHandle, byte _PM);
	/**
	 * Original signature : <code>int K2616_AutoTestICCard(HANDLE, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:62</i><br>
	 * @deprecated use the safer methods {@link #K2616_AutoTestICCard(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_AutoTestICCard(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AutoTestICCard(HANDLE ComHandle, Pointer _IcCardType);
	/**
	 * Original signature : <code>int K2616_AutoTestICCard(HANDLE, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:62</i>
	 */
	int K2616_AutoTestICCard(HANDLE ComHandle, ByteBuffer _IcCardType);
	/**
	 * Original signature : <code>int K2616_AutoTestRFIDCard(HANDLE, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:63</i><br>
	 * @deprecated use the safer methods {@link #K2616_AutoTestRFIDCard(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_AutoTestRFIDCard(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AutoTestRFIDCard(HANDLE ComHandle, Pointer _RFIDCardType);
	/**
	 * Original signature : <code>int K2616_AutoTestRFIDCard(HANDLE, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:63</i>
	 */
	int K2616_AutoTestRFIDCard(HANDLE ComHandle, ByteBuffer _RFIDCardType);
	/**
	 * Original signature : <code>int K2616_PowerOn(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:64</i>
	 */
	int K2616_PowerOn(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_PowerOff(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:65</i>
	 */
	int K2616_PowerOff(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_Led1Control(HANDLE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:66</i>
	 */
	int K2616_Led1Control(HANDLE ComHandle, byte _PM);
	/**
	 * Original signature : <code>int K2616_SetLedFlickerRate(HANDLE, BYTE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:67</i>
	 */
	int K2616_SetLedFlickerRate(HANDLE ComHandle, byte _PM, byte _Rate);
	/**
	 * Original signature : <code>int K2616_Led2Control(HANDLE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:68</i>
	 */
	int K2616_Led2Control(HANDLE ComHandle, byte _PM);
	/**
	 * Original signature : <code>int K2616_ReadBarcode(HANDLE, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:69</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadBarcode(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_ReadBarcode(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadBarcode(HANDLE ComHandle, Pointer szData);
	/**
	 * Original signature : <code>int K2616_ReadBarcode(HANDLE, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:69</i>
	 */
	int K2616_ReadBarcode(HANDLE ComHandle, ByteBuffer szData);
	/**
	 * Original signature : <code>int K2616_Eot(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:70</i>
	 */
	int K2616_Eot(HANDLE ComHandle);
	/**
	 * ++++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_ReadMagcardDecode(HANDLE, BYTE, DWORD*, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:72</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadMagcardDecode(k2616_dll.K2616_DllLibrary.HANDLE, byte, IntBuffer, ByteBuffer)} and {@link #K2616_ReadMagcardDecode(k2616_dll.K2616_DllLibrary.HANDLE, byte, IntByReference, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadMagcardDecode(HANDLE ComHandle, byte _track, IntByReference _DataLen, Pointer _BlockData);
	/**
	 * ++++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_ReadMagcardDecode(HANDLE, BYTE, DWORD*, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:72</i>
	 */
	int K2616_ReadMagcardDecode(HANDLE ComHandle, byte _track, IntBuffer _DataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_ReadMagcardUNDecode(HANDLE, BYTE, DWORD*, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:73</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadMagcardUNDecode(k2616_dll.K2616_DllLibrary.HANDLE, byte, IntBuffer, ByteBuffer)} and {@link #K2616_ReadMagcardUNDecode(k2616_dll.K2616_DllLibrary.HANDLE, byte, IntByReference, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadMagcardUNDecode(HANDLE ComHandle, byte _track, IntByReference _DataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_ReadMagcardUNDecode(HANDLE, BYTE, DWORD*, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:73</i>
	 */
	int K2616_ReadMagcardUNDecode(HANDLE ComHandle, byte _track, IntBuffer _DataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_ClearMagCardData(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:74</i>
	 */
	int K2616_ClearMagCardData(HANDLE ComHandle);
	/**
	 * ++++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_S50DetectCard(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:76</i>
	 */
	int K2616_S50DetectCard(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_S50GetCardID(HANDLE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:77</i><br>
	 * @deprecated use the safer methods {@link #K2616_S50GetCardID(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_S50GetCardID(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S50GetCardID(HANDLE ComHandle, Pointer _CardID);
	/**
	 * Original signature : <code>int K2616_S50GetCardID(HANDLE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:77</i>
	 */
	int K2616_S50GetCardID(HANDLE ComHandle, ByteBuffer _CardID);
	/**
	 * Original signature : <code>int K2616_S50LoadSecKey(HANDLE, BYTE, BYTE, BYTE[6])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:78</i><br>
	 * @deprecated use the safer methods {@link #K2616_S50LoadSecKey(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, ByteBuffer)} and {@link #K2616_S50LoadSecKey(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S50LoadSecKey(HANDLE ComHandle, byte _BlockAddr, byte _KEYType, Pointer _KEY);
	/**
	 * Original signature : <code>int K2616_S50LoadSecKey(HANDLE, BYTE, BYTE, BYTE[6])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:78</i>
	 */
	int K2616_S50LoadSecKey(HANDLE ComHandle, byte _BlockAddr, byte _KEYType, ByteBuffer _KEY);
	/**
	 * Original signature : <code>int K2616_S50ReadBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:79</i><br>
	 * @deprecated use the safer methods {@link #K2616_S50ReadBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_S50ReadBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S50ReadBlock(HANDLE ComHandle, byte _Block, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_S50ReadBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:79</i>
	 */
	int K2616_S50ReadBlock(HANDLE ComHandle, byte _Block, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_S50WriteBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:80</i><br>
	 * @deprecated use the safer methods {@link #K2616_S50WriteBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_S50WriteBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S50WriteBlock(HANDLE ComHandle, byte _Block, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_S50WriteBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:80</i>
	 */
	int K2616_S50WriteBlock(HANDLE ComHandle, byte _Block, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_S50InitValue(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:81</i><br>
	 * @deprecated use the safer methods {@link #K2616_S50InitValue(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_S50InitValue(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S50InitValue(HANDLE ComHandle, byte _Block, Pointer _Data);
	/**
	 * Original signature : <code>int K2616_S50InitValue(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:81</i>
	 */
	int K2616_S50InitValue(HANDLE ComHandle, byte _Block, ByteBuffer _Data);
	/**
	 * Original signature : <code>int K2616_S50Increment(HANDLE, BYTE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:82</i><br>
	 * @deprecated use the safer methods {@link #K2616_S50Increment(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_S50Increment(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S50Increment(HANDLE ComHandle, byte _Block, Pointer _Data);
	/**
	 * Original signature : <code>int K2616_S50Increment(HANDLE, BYTE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:82</i>
	 */
	int K2616_S50Increment(HANDLE ComHandle, byte _Block, ByteBuffer _Data);
	/**
	 * Original signature : <code>int K2616_S50Decrement(HANDLE, BYTE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:83</i><br>
	 * @deprecated use the safer methods {@link #K2616_S50Decrement(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_S50Decrement(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S50Decrement(HANDLE ComHandle, byte _Block, Pointer _Data);
	/**
	 * Original signature : <code>int K2616_S50Decrement(HANDLE, BYTE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:83</i>
	 */
	int K2616_S50Decrement(HANDLE ComHandle, byte _Block, ByteBuffer _Data);
	/**
	 * Original signature : <code>int K2616_S50Halt(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:84</i>
	 */
	int K2616_S50Halt(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_S70DetectCard(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:85</i>
	 */
	int K2616_S70DetectCard(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_S70GetCardID(HANDLE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:86</i><br>
	 * @deprecated use the safer methods {@link #K2616_S70GetCardID(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_S70GetCardID(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S70GetCardID(HANDLE ComHandle, Pointer _CardID);
	/**
	 * Original signature : <code>int K2616_S70GetCardID(HANDLE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:86</i>
	 */
	int K2616_S70GetCardID(HANDLE ComHandle, ByteBuffer _CardID);
	/**
	 * Original signature : <code>int K2616_S70LoadSecKey(HANDLE, BYTE, BYTE, BYTE[6])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:87</i><br>
	 * @deprecated use the safer methods {@link #K2616_S70LoadSecKey(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, ByteBuffer)} and {@link #K2616_S70LoadSecKey(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S70LoadSecKey(HANDLE ComHandle, byte _BlockAddr, byte _KEYType, Pointer _KEY);
	/**
	 * Original signature : <code>int K2616_S70LoadSecKey(HANDLE, BYTE, BYTE, BYTE[6])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:87</i>
	 */
	int K2616_S70LoadSecKey(HANDLE ComHandle, byte _BlockAddr, byte _KEYType, ByteBuffer _KEY);
	/**
	 * Original signature : <code>int K2616_S70ReadBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:88</i><br>
	 * @deprecated use the safer methods {@link #K2616_S70ReadBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_S70ReadBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S70ReadBlock(HANDLE ComHandle, byte _Block, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_S70ReadBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:88</i>
	 */
	int K2616_S70ReadBlock(HANDLE ComHandle, byte _Block, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_S70WriteBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:89</i><br>
	 * @deprecated use the safer methods {@link #K2616_S70WriteBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_S70WriteBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S70WriteBlock(HANDLE ComHandle, byte _Block, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_S70WriteBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:89</i>
	 */
	int K2616_S70WriteBlock(HANDLE ComHandle, byte _Block, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_S70InitValue(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:90</i><br>
	 * @deprecated use the safer methods {@link #K2616_S70InitValue(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_S70InitValue(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S70InitValue(HANDLE ComHandle, byte _Block, Pointer _Data);
	/**
	 * Original signature : <code>int K2616_S70InitValue(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:90</i>
	 */
	int K2616_S70InitValue(HANDLE ComHandle, byte _Block, ByteBuffer _Data);
	/**
	 * Original signature : <code>int K2616_S70Increment(HANDLE, BYTE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:91</i><br>
	 * @deprecated use the safer methods {@link #K2616_S70Increment(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_S70Increment(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S70Increment(HANDLE ComHandle, byte _Block, Pointer _Data);
	/**
	 * Original signature : <code>int K2616_S70Increment(HANDLE, BYTE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:91</i>
	 */
	int K2616_S70Increment(HANDLE ComHandle, byte _Block, ByteBuffer _Data);
	/**
	 * Original signature : <code>int K2616_S70Decrement(HANDLE, BYTE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:92</i><br>
	 * @deprecated use the safer methods {@link #K2616_S70Decrement(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_S70Decrement(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_S70Decrement(HANDLE ComHandle, byte _Block, Pointer _Data);
	/**
	 * Original signature : <code>int K2616_S70Decrement(HANDLE, BYTE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:92</i>
	 */
	int K2616_S70Decrement(HANDLE ComHandle, byte _Block, ByteBuffer _Data);
	/**
	 * Original signature : <code>int K2616_S70Halt(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:93</i>
	 */
	int K2616_S70Halt(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_ULDetectCard(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:94</i>
	 */
	int K2616_ULDetectCard(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_ULGetCardID(HANDLE, BYTE[7])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:95</i><br>
	 * @deprecated use the safer methods {@link #K2616_ULGetCardID(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_ULGetCardID(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ULGetCardID(HANDLE ComHandle, Pointer _CardID);
	/**
	 * Original signature : <code>int K2616_ULGetCardID(HANDLE, BYTE[7])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:95</i>
	 */
	int K2616_ULGetCardID(HANDLE ComHandle, ByteBuffer _CardID);
	/**
	 * Original signature : <code>int K2616_ULReadBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:96</i><br>
	 * @deprecated use the safer methods {@link #K2616_ULReadBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_ULReadBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ULReadBlock(HANDLE ComHandle, byte _Block, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_ULReadBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:96</i>
	 */
	int K2616_ULReadBlock(HANDLE ComHandle, byte _Block, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_ULWriteBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:97</i><br>
	 * @deprecated use the safer methods {@link #K2616_ULWriteBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_ULWriteBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ULWriteBlock(HANDLE ComHandle, byte _Block, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_ULWriteBlock(HANDLE, BYTE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:97</i>
	 */
	int K2616_ULWriteBlock(HANDLE ComHandle, byte _Block, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_ULHalt(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:98</i>
	 */
	int K2616_ULHalt(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_15693GetUid(HANDLE, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:99</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693GetUid(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_15693GetUid(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_15693GetUid(HANDLE ComHandle, Pointer UID);
	/**
	 * Original signature : <code>int K2616_15693GetUid(HANDLE, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:99</i>
	 */
	int K2616_15693GetUid(HANDLE ComHandle, ByteBuffer UID);
	/**
	 * Original signature : <code>int K2616_15693ReadData(HANDLE, bool, BYTE[8], BYTE, BYTE, BYTE[], BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:100</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693ReadData(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer, byte, byte, ByteBuffer, ByteBuffer)} and {@link #K2616_15693ReadData(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer, byte, byte, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_15693ReadData(HANDLE ComHandle, byte bUid, Pointer Uid, byte BlockAddr, byte BlockLen, Pointer _BlockData, Pointer ReadBlockLen);
	/**
	 * Original signature : <code>int K2616_15693ReadData(HANDLE, bool, BYTE[8], BYTE, BYTE, BYTE[], BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:100</i>
	 */
	int K2616_15693ReadData(HANDLE ComHandle, byte bUid, ByteBuffer Uid, byte BlockAddr, byte BlockLen, ByteBuffer _BlockData, ByteBuffer ReadBlockLen);
	/**
	 * Original signature : <code>int K2616_15693WriteData(HANDLE, bool, BYTE[8], BYTE, BYTE, BYTE[], BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:101</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693WriteData(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer, byte, byte, ByteBuffer, ByteBuffer)} and {@link #K2616_15693WriteData(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer, byte, byte, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_15693WriteData(HANDLE ComHandle, byte bUid, Pointer Uid, byte BlockAddr, byte BlockLen, Pointer _BlockData, Pointer WriteBlockLen);
	/**
	 * Original signature : <code>int K2616_15693WriteData(HANDLE, bool, BYTE[8], BYTE, BYTE, BYTE[], BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:101</i>
	 */
	int K2616_15693WriteData(HANDLE ComHandle, byte bUid, ByteBuffer Uid, byte BlockAddr, byte BlockLen, ByteBuffer _BlockData, ByteBuffer WriteBlockLen);
	/**
	 * Original signature : <code>int K2616_15693ChooseCard(HANDLE, bool, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:102</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693ChooseCard(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_15693ChooseCard(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_15693ChooseCard(HANDLE ComHandle, byte bUid, Pointer Uid);
	/**
	 * Original signature : <code>int K2616_15693ChooseCard(HANDLE, bool, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:102</i>
	 */
	int K2616_15693ChooseCard(HANDLE ComHandle, byte bUid, ByteBuffer Uid);
	/**
	 * Original signature : <code>int K2616_15693GetMessage(HANDLE, bool, BYTE[8], BYTE[15])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:103</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693GetMessage(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer, ByteBuffer)} and {@link #K2616_15693GetMessage(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_15693GetMessage(HANDLE ComHandle, byte bUid, Pointer Uid, Pointer Message);
	/**
	 * Original signature : <code>int K2616_15693GetMessage(HANDLE, bool, BYTE[8], BYTE[15])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:103</i>
	 */
	int K2616_15693GetMessage(HANDLE ComHandle, byte bUid, ByteBuffer Uid, ByteBuffer Message);
	/**
	 * Original signature : <code>int K2616_15693ReadSafeBit(HANDLE, bool, BYTE[8], BYTE, BYTE, BYTE*, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:104</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693ReadSafeBit(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer, byte, byte, ByteBuffer, ByteBuffer)} and {@link #K2616_15693ReadSafeBit(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer, byte, byte, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_15693ReadSafeBit(HANDLE ComHandle, byte bUid, Pointer Uid, byte BlockAddr, byte BlockLen, Pointer ReadBlockLen, Pointer BlockLockStatus);
	/**
	 * Original signature : <code>int K2616_15693ReadSafeBit(HANDLE, bool, BYTE[8], BYTE, BYTE, BYTE*, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:104</i>
	 */
	int K2616_15693ReadSafeBit(HANDLE ComHandle, byte bUid, ByteBuffer Uid, byte BlockAddr, byte BlockLen, ByteBuffer ReadBlockLen, ByteBuffer BlockLockStatus);
	/**
	 * Original signature : <code>int K2616_15693WriteDSFID(HANDLE, bool, BYTE[8], BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:105</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693WriteDSFID(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer, byte)} and {@link #K2616_15693WriteDSFID(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer, byte)} instead
	 */
	@Deprecated 
	int K2616_15693WriteDSFID(HANDLE ComHandle, byte bUid, Pointer Uid, byte WriteBit);
	/**
	 * Original signature : <code>int K2616_15693WriteDSFID(HANDLE, bool, BYTE[8], BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:105</i>
	 */
	int K2616_15693WriteDSFID(HANDLE ComHandle, byte bUid, ByteBuffer Uid, byte WriteBit);
	/**
	 * Original signature : <code>int K2616_15693WriteAFI(HANDLE, bool, BYTE[8], BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:106</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693WriteAFI(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer, byte)} and {@link #K2616_15693WriteAFI(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer, byte)} instead
	 */
	@Deprecated 
	int K2616_15693WriteAFI(HANDLE ComHandle, byte bUid, Pointer Uid, byte WriteBit);
	/**
	 * Original signature : <code>int K2616_15693WriteAFI(HANDLE, bool, BYTE[8], BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:106</i>
	 */
	int K2616_15693WriteAFI(HANDLE ComHandle, byte bUid, ByteBuffer Uid, byte WriteBit);
	/**
	 * Original signature : <code>int K2616_15693LockBlock(HANDLE, bool, BYTE[8], BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:107</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693LockBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer, byte)} and {@link #K2616_15693LockBlock(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer, byte)} instead
	 */
	@Deprecated 
	int K2616_15693LockBlock(HANDLE ComHandle, byte bUid, Pointer Uid, byte LockAddress);
	/**
	 * Original signature : <code>int K2616_15693LockBlock(HANDLE, bool, BYTE[8], BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:107</i>
	 */
	int K2616_15693LockBlock(HANDLE ComHandle, byte bUid, ByteBuffer Uid, byte LockAddress);
	/**
	 * Original signature : <code>int K2616_15693LockAFI(HANDLE, bool, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:108</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693LockAFI(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_15693LockAFI(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_15693LockAFI(HANDLE ComHandle, byte bUid, Pointer Uid);
	/**
	 * Original signature : <code>int K2616_15693LockAFI(HANDLE, bool, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:108</i>
	 */
	int K2616_15693LockAFI(HANDLE ComHandle, byte bUid, ByteBuffer Uid);
	/**
	 * Original signature : <code>int K2616_15693LockDSFID(HANDLE, bool, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:109</i><br>
	 * @deprecated use the safer methods {@link #K2616_15693LockDSFID(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_15693LockDSFID(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_15693LockDSFID(HANDLE ComHandle, byte bUid, Pointer Uid);
	/**
	 * Original signature : <code>int K2616_15693LockDSFID(HANDLE, bool, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:109</i>
	 */
	int K2616_15693LockDSFID(HANDLE ComHandle, byte bUid, ByteBuffer Uid);
	/**
	 * Original signature : <code>int K2616_GetIdCardNo(HANDLE, char[10])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:111</i><br>
	 * @deprecated use the safer methods {@link #K2616_GetIdCardNo(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_GetIdCardNo(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_GetIdCardNo(HANDLE ComHandle, Pointer Id);
	/**
	 * Original signature : <code>int K2616_GetIdCardNo(HANDLE, char[10])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:111</i>
	 */
	int K2616_GetIdCardNo(HANDLE ComHandle, ByteBuffer Id);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_IcCardPowerOn(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:115</i>
	 */
	int K2616_IcCardPowerOn(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_IcCardPowerOff(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:116</i>
	 */
	int K2616_IcCardPowerOff(HANDLE ComHandle);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_CpuCardColdReset(HANDLE, BYTE*, BYTE[], BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:118</i><br>
	 * @deprecated use the safer methods {@link #K2616_CpuCardColdReset(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer, ByteBuffer, ByteBuffer)} and {@link #K2616_CpuCardColdReset(k2616_dll.K2616_DllLibrary.HANDLE, Pointer, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_CpuCardColdReset(HANDLE ComHandle, Pointer _CPUType, Pointer _RstData, Pointer _RstdataLen);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_CpuCardColdReset(HANDLE, BYTE*, BYTE[], BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:118</i>
	 */
	int K2616_CpuCardColdReset(HANDLE ComHandle, ByteBuffer _CPUType, ByteBuffer _RstData, ByteBuffer _RstdataLen);
	/**
	 * Original signature : <code>int K2616_CpuCardPowerOff(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:119</i>
	 */
	int K2616_CpuCardPowerOff(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_CpuCardWarmReset(HANDLE, BYTE, BYTE*, BYTE[], BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:120</i><br>
	 * @deprecated use the safer methods {@link #K2616_CpuCardWarmReset(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer, ByteBuffer, ByteBuffer)} and {@link #K2616_CpuCardWarmReset(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_CpuCardWarmReset(HANDLE ComHandle, byte _VOLTAGE, Pointer _CPUType, Pointer _RstData, Pointer _RstdataLen);
	/**
	 * Original signature : <code>int K2616_CpuCardWarmReset(HANDLE, BYTE, BYTE*, BYTE[], BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:120</i>
	 */
	int K2616_CpuCardWarmReset(HANDLE ComHandle, byte _VOLTAGE, ByteBuffer _CPUType, ByteBuffer _RstData, ByteBuffer _RstdataLen);
	/**
	 * Original signature : <code>int K2616_CPUT0APDU(HANDLE, int, BYTE[], BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:121</i><br>
	 * @deprecated use the safer methods {@link #K2616_CPUT0APDU(k2616_dll.K2616_DllLibrary.HANDLE, int, ByteBuffer, ByteBuffer, IntBuffer)} and {@link #K2616_CPUT0APDU(k2616_dll.K2616_DllLibrary.HANDLE, int, Pointer, Pointer, IntByReference)} instead
	 */
	@Deprecated 
	int K2616_CPUT0APDU(HANDLE ComHandle, int _dataLen, Pointer _APDUData, Pointer _exData, IntByReference _exdataLen);
	/**
	 * Original signature : <code>int K2616_CPUT0APDU(HANDLE, int, BYTE[], BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:121</i>
	 */
	int K2616_CPUT0APDU(HANDLE ComHandle, int _dataLen, ByteBuffer _APDUData, ByteBuffer _exData, IntBuffer _exdataLen);
	/**
	 * Original signature : <code>int K2616_CPUT1APDU(HANDLE, int, BYTE[], BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:122</i><br>
	 * @deprecated use the safer methods {@link #K2616_CPUT1APDU(k2616_dll.K2616_DllLibrary.HANDLE, int, ByteBuffer, ByteBuffer, IntBuffer)} and {@link #K2616_CPUT1APDU(k2616_dll.K2616_DllLibrary.HANDLE, int, Pointer, Pointer, IntByReference)} instead
	 */
	@Deprecated 
	int K2616_CPUT1APDU(HANDLE ComHandle, int _dataLen, Pointer _APDUData, Pointer _exData, IntByReference _exdataLen);
	/**
	 * Original signature : <code>int K2616_CPUT1APDU(HANDLE, int, BYTE[], BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:122</i>
	 */
	int K2616_CPUT1APDU(HANDLE ComHandle, int _dataLen, ByteBuffer _APDUData, ByteBuffer _exData, IntBuffer _exdataLen);
	/**
	 * Original signature : <code>int K2616_ReadInfoPOP(HANDLE, BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:123</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadInfoPOP(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer, IntBuffer)} and {@link #K2616_ReadInfoPOP(k2616_dll.K2616_DllLibrary.HANDLE, Pointer, IntByReference)} instead
	 */
	@Deprecated 
	int K2616_ReadInfoPOP(HANDLE ComHandle, Pointer _exData, IntByReference _exdataLen);
	/**
	 * Original signature : <code>int K2616_ReadInfoPOP(HANDLE, BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:123</i>
	 */
	int K2616_ReadInfoPOP(HANDLE ComHandle, ByteBuffer _exData, IntBuffer _exdataLen);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_SimColdReset(HANDLE, BYTE*, BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:125</i><br>
	 * @deprecated use the safer methods {@link #K2616_SimColdReset(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer, ByteBuffer, IntBuffer)} and {@link #K2616_SimColdReset(k2616_dll.K2616_DllLibrary.HANDLE, Pointer, Pointer, IntByReference)} instead
	 */
	@Deprecated 
	int K2616_SimColdReset(HANDLE ComHandle, Pointer _SIMTYPE, Pointer _exData, IntByReference _exdataLen);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_SimColdReset(HANDLE, BYTE*, BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:125</i>
	 */
	int K2616_SimColdReset(HANDLE ComHandle, ByteBuffer _SIMTYPE, ByteBuffer _exData, IntBuffer _exdataLen);
	/**
	 * Original signature : <code>int K2616_SimCardPowerOff(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:126</i>
	 */
	int K2616_SimCardPowerOff(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_SimT0APDU(HANDLE, int, BYTE[], BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:127</i><br>
	 * @deprecated use the safer methods {@link #K2616_SimT0APDU(k2616_dll.K2616_DllLibrary.HANDLE, int, ByteBuffer, ByteBuffer, IntBuffer)} and {@link #K2616_SimT0APDU(k2616_dll.K2616_DllLibrary.HANDLE, int, Pointer, Pointer, IntByReference)} instead
	 */
	@Deprecated 
	int K2616_SimT0APDU(HANDLE ComHandle, int _dataLen, Pointer _APDUData, Pointer _exData, IntByReference _exdataLen);
	/**
	 * Original signature : <code>int K2616_SimT0APDU(HANDLE, int, BYTE[], BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:127</i>
	 */
	int K2616_SimT0APDU(HANDLE ComHandle, int _dataLen, ByteBuffer _APDUData, ByteBuffer _exData, IntBuffer _exdataLen);
	/**
	 * Original signature : <code>int K2616_SimT1APDU(HANDLE, int, BYTE[], BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:128</i><br>
	 * @deprecated use the safer methods {@link #K2616_SimT1APDU(k2616_dll.K2616_DllLibrary.HANDLE, int, ByteBuffer, ByteBuffer, IntBuffer)} and {@link #K2616_SimT1APDU(k2616_dll.K2616_DllLibrary.HANDLE, int, Pointer, Pointer, IntByReference)} instead
	 */
	@Deprecated 
	int K2616_SimT1APDU(HANDLE ComHandle, int _dataLen, Pointer _APDUData, Pointer _exData, IntByReference _exdataLen);
	/**
	 * Original signature : <code>int K2616_SimT1APDU(HANDLE, int, BYTE[], BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:128</i>
	 */
	int K2616_SimT1APDU(HANDLE ComHandle, int _dataLen, ByteBuffer _APDUData, ByteBuffer _exData, IntBuffer _exdataLen);
	/**
	 * Original signature : <code>int K2616_SimSelect(HANDLE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:129</i>
	 */
	int K2616_SimSelect(HANDLE ComHandle, byte SIMNo);
	/**
	 * Original signature : <code>int K2616_SimWarmReset(HANDLE, BYTE, BYTE*, BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:130</i><br>
	 * @deprecated use the safer methods {@link #K2616_SimWarmReset(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer, ByteBuffer, IntBuffer)} and {@link #K2616_SimWarmReset(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer, Pointer, IntByReference)} instead
	 */
	@Deprecated 
	int K2616_SimWarmReset(HANDLE ComHandle, byte _VOLTAGE, Pointer _SIMTYPE, Pointer _exData, IntByReference _exdataLen);
	/**
	 * Original signature : <code>int K2616_SimWarmReset(HANDLE, BYTE, BYTE*, BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:130</i>
	 */
	int K2616_SimWarmReset(HANDLE ComHandle, byte _VOLTAGE, ByteBuffer _SIMTYPE, ByteBuffer _exData, IntBuffer _exdataLen);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_AT24CXXRead(HANDLE, BYTE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:132</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT24CXXRead(k2616_dll.K2616_DllLibrary.HANDLE, byte, int, byte, ByteBuffer)} and {@link #K2616_AT24CXXRead(k2616_dll.K2616_DllLibrary.HANDLE, byte, int, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT24CXXRead(HANDLE ComHandle, byte _CardType, int _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_AT24CXXRead(HANDLE, BYTE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:132</i>
	 */
	int K2616_AT24CXXRead(HANDLE ComHandle, byte _CardType, int _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT24CXXWrite(HANDLE, BYTE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:133</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT24CXXWrite(k2616_dll.K2616_DllLibrary.HANDLE, byte, int, byte, ByteBuffer)} and {@link #K2616_AT24CXXWrite(k2616_dll.K2616_DllLibrary.HANDLE, byte, int, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT24CXXWrite(HANDLE ComHandle, byte _CardType, int _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT24CXXWrite(HANDLE, BYTE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:133</i>
	 */
	int K2616_AT24CXXWrite(HANDLE ComHandle, byte _CardType, int _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_AT45DB041Reset(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:135</i>
	 */
	int K2616_AT45DB041Reset(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_AT45DB041Read(HANDLE, int, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:136</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT45DB041Read(k2616_dll.K2616_DllLibrary.HANDLE, int, ByteBuffer)} and {@link #K2616_AT45DB041Read(k2616_dll.K2616_DllLibrary.HANDLE, int, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT45DB041Read(HANDLE ComHandle, int _Address, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT45DB041Read(HANDLE, int, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:136</i>
	 */
	int K2616_AT45DB041Read(HANDLE ComHandle, int _Address, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT45DB041Write(HANDLE, int, BYTE[264])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:137</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT45DB041Write(k2616_dll.K2616_DllLibrary.HANDLE, int, ByteBuffer)} and {@link #K2616_AT45DB041Write(k2616_dll.K2616_DllLibrary.HANDLE, int, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT45DB041Write(HANDLE ComHandle, int _Address, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT45DB041Write(HANDLE, int, BYTE[264])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:137</i>
	 */
	int K2616_AT45DB041Write(HANDLE ComHandle, int _Address, ByteBuffer _BlockData);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_AT88SC102Reset(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:139</i>
	 */
	int K2616_AT88SC102Reset(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_AT88SC102VerifyPWD(HANDLE, BYTE[2])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:140</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC102VerifyPWD(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_AT88SC102VerifyPWD(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC102VerifyPWD(HANDLE ComHandle, Pointer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC102VerifyPWD(HANDLE, BYTE[2])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:140</i>
	 */
	int K2616_AT88SC102VerifyPWD(HANDLE ComHandle, ByteBuffer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC102Read(HANDLE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:141</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC102Read(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, ByteBuffer)} and {@link #K2616_AT88SC102Read(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC102Read(HANDLE ComHandle, byte _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC102Read(HANDLE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:141</i>
	 */
	int K2616_AT88SC102Read(HANDLE ComHandle, byte _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC102Security1Erasure(HANDLE, BYTE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:142</i>
	 */
	int K2616_AT88SC102Security1Erasure(HANDLE ComHandle, byte _Address, byte _dataLen);
	/**
	 * Original signature : <code>int K2616_AT88SC102Security2ErasureApp1(HANDLE, BYTE[6])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:143</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC102Security2ErasureApp1(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_AT88SC102Security2ErasureApp1(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC102Security2ErasureApp1(HANDLE ComHandle, Pointer _Security2App1PW);
	/**
	 * Original signature : <code>int K2616_AT88SC102Security2ErasureApp1(HANDLE, BYTE[6])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:143</i>
	 */
	int K2616_AT88SC102Security2ErasureApp1(HANDLE ComHandle, ByteBuffer _Security2App1PW);
	/**
	 * Original signature : <code>int K2616_AT88SC102Security2ErasureApp2(HANDLE, BYTE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:144</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC102Security2ErasureApp2(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_AT88SC102Security2ErasureApp2(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC102Security2ErasureApp2(HANDLE ComHandle, byte _EC2, Pointer _Security2App2PW);
	/**
	 * Original signature : <code>int K2616_AT88SC102Security2ErasureApp2(HANDLE, BYTE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:144</i>
	 */
	int K2616_AT88SC102Security2ErasureApp2(HANDLE ComHandle, byte _EC2, ByteBuffer _Security2App2PW);
	/**
	 * Original signature : <code>int K2616_AT88SC102Write(HANDLE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:145</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC102Write(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, ByteBuffer)} and {@link #K2616_AT88SC102Write(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC102Write(HANDLE ComHandle, byte _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC102Write(HANDLE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:145</i>
	 */
	int K2616_AT88SC102Write(HANDLE ComHandle, byte _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC102WritePWD(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:146</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC102WritePWD(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_AT88SC102WritePWD(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC102WritePWD(HANDLE ComHandle, byte _PWType, Pointer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC102WritePWD(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:146</i>
	 */
	int K2616_AT88SC102WritePWD(HANDLE ComHandle, byte _PWType, ByteBuffer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC102SetMode(HANDLE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:147</i>
	 */
	int K2616_AT88SC102SetMode(HANDLE ComHandle, byte _CtrlMode);
	/**
	 * Original signature : <code>int K2616_AT88SC102DisableEC2(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:148</i>
	 */
	int K2616_AT88SC102DisableEC2(HANDLE ComHandle);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_AT88SC1604Reset(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:150</i>
	 */
	int K2616_AT88SC1604Reset(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_AT88SC1604VerifyPWD(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:151</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1604VerifyPWD(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_AT88SC1604VerifyPWD(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1604VerifyPWD(HANDLE ComHandle, byte _PWType, Pointer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC1604VerifyPWD(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:151</i>
	 */
	int K2616_AT88SC1604VerifyPWD(HANDLE ComHandle, byte _PWType, ByteBuffer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC1604Read(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:152</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1604Read(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, ByteBuffer)} and {@link #K2616_AT88SC1604Read(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1604Read(HANDLE ComHandle, int _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC1604Read(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:152</i>
	 */
	int K2616_AT88SC1604Read(HANDLE ComHandle, int _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC1604Erasure(HANDLE, int, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:153</i>
	 */
	int K2616_AT88SC1604Erasure(HANDLE ComHandle, int _Address, byte _dataLen);
	/**
	 * Original signature : <code>int K2616_AT88SC1604Write(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:154</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1604Write(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, ByteBuffer)} and {@link #K2616_AT88SC1604Write(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1604Write(HANDLE ComHandle, int _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC1604Write(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:154</i>
	 */
	int K2616_AT88SC1604Write(HANDLE ComHandle, int _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC1604WritePWD(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:155</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1604WritePWD(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_AT88SC1604WritePWD(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1604WritePWD(HANDLE ComHandle, byte _PWType, Pointer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC1604WritePWD(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:155</i>
	 */
	int K2616_AT88SC1604WritePWD(HANDLE ComHandle, byte _PWType, ByteBuffer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC1604Personalization(HANDLE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:156</i>
	 */
	int K2616_AT88SC1604Personalization(HANDLE ComHandle, byte _PM);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_AT88SC1608Reset(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:158</i>
	 */
	int K2616_AT88SC1608Reset(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_AT88SC1608VerifyPWD(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:159</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1608VerifyPWD(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_AT88SC1608VerifyPWD(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1608VerifyPWD(HANDLE ComHandle, byte _PWType, Pointer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC1608VerifyPWD(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:159</i>
	 */
	int K2616_AT88SC1608VerifyPWD(HANDLE ComHandle, byte _PWType, ByteBuffer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC1608Read(HANDLE, BYTE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:160</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1608Read(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, byte, ByteBuffer)} and {@link #K2616_AT88SC1608Read(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1608Read(HANDLE ComHandle, byte _Index, byte _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC1608Read(HANDLE, BYTE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:160</i>
	 */
	int K2616_AT88SC1608Read(HANDLE ComHandle, byte _Index, byte _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC1608Write(HANDLE, BYTE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:161</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1608Write(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, byte, ByteBuffer)} and {@link #K2616_AT88SC1608Write(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1608Write(HANDLE ComHandle, byte _Index, byte _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC1608Write(HANDLE, BYTE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:161</i>
	 */
	int K2616_AT88SC1608Write(HANDLE ComHandle, byte _Index, byte _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_AT88SC1608ReadFUSE(HANDLE, BYTE*, BYTE*, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:162</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1608ReadFUSE(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer, ByteBuffer, ByteBuffer)} and {@link #K2616_AT88SC1608ReadFUSE(k2616_dll.K2616_DllLibrary.HANDLE, Pointer, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1608ReadFUSE(HANDLE ComHandle, Pointer _FAB, Pointer _CMA, Pointer _PER);
	/**
	 * Original signature : <code>int K2616_AT88SC1608ReadFUSE(HANDLE, BYTE*, BYTE*, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:162</i>
	 */
	int K2616_AT88SC1608ReadFUSE(HANDLE ComHandle, ByteBuffer _FAB, ByteBuffer _CMA, ByteBuffer _PER);
	/**
	 * Original signature : <code>int K2616_AT88SC1608WriteFUSE(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:163</i>
	 */
	int K2616_AT88SC1608WriteFUSE(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_AT88SC1608InitAuth(HANDLE, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:164</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1608InitAuth(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_AT88SC1608InitAuth(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1608InitAuth(HANDLE ComHandle, Pointer _DATA);
	/**
	 * Original signature : <code>int K2616_AT88SC1608InitAuth(HANDLE, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:164</i>
	 */
	int K2616_AT88SC1608InitAuth(HANDLE ComHandle, ByteBuffer _DATA);
	/**
	 * Original signature : <code>int K2616_AT88SC1608VerifyAuth(HANDLE, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:165</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1608VerifyAuth(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_AT88SC1608VerifyAuth(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1608VerifyAuth(HANDLE ComHandle, Pointer _DATA);
	/**
	 * Original signature : <code>int K2616_AT88SC1608VerifyAuth(HANDLE, BYTE[8])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:165</i>
	 */
	int K2616_AT88SC1608VerifyAuth(HANDLE ComHandle, ByteBuffer _DATA);
	/**
	 * Original signature : <code>int K2616_AT88SC1608WritePWD(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:166</i><br>
	 * @deprecated use the safer methods {@link #K2616_AT88SC1608WritePWD(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_AT88SC1608WritePWD(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AT88SC1608WritePWD(HANDLE ComHandle, byte _PWType, Pointer _PWData);
	/**
	 * Original signature : <code>int K2616_AT88SC1608WritePWD(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:166</i>
	 */
	int K2616_AT88SC1608WritePWD(HANDLE ComHandle, byte _PWType, ByteBuffer _PWData);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_SLE4442Reset(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:168</i>
	 */
	int K2616_SLE4442Reset(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_SLE4442VerifyPWD(HANDLE, BYTE[3])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:169</i><br>
	 * @deprecated use the safer methods {@link #K2616_SLE4442VerifyPWD(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_SLE4442VerifyPWD(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_SLE4442VerifyPWD(HANDLE ComHandle, Pointer _PWData);
	/**
	 * Original signature : <code>int K2616_SLE4442VerifyPWD(HANDLE, BYTE[3])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:169</i>
	 */
	int K2616_SLE4442VerifyPWD(HANDLE ComHandle, ByteBuffer _PWData);
	/**
	 * Original signature : <code>int K2616_SLE4442Read(HANDLE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:170</i><br>
	 * @deprecated use the safer methods {@link #K2616_SLE4442Read(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, ByteBuffer)} and {@link #K2616_SLE4442Read(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_SLE4442Read(HANDLE ComHandle, byte _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_SLE4442Read(HANDLE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:170</i>
	 */
	int K2616_SLE4442Read(HANDLE ComHandle, byte _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_SLE4442ReadProtectBit(HANDLE, BYTE[32])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:171</i><br>
	 * @deprecated use the safer methods {@link #K2616_SLE4442ReadProtectBit(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_SLE4442ReadProtectBit(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_SLE4442ReadProtectBit(HANDLE ComHandle, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_SLE4442ReadProtectBit(HANDLE, BYTE[32])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:171</i>
	 */
	int K2616_SLE4442ReadProtectBit(HANDLE ComHandle, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_SLE4442ReadSafety(HANDLE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:172</i><br>
	 * @deprecated use the safer methods {@link #K2616_SLE4442ReadSafety(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_SLE4442ReadSafety(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_SLE4442ReadSafety(HANDLE ComHandle, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_SLE4442ReadSafety(HANDLE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:172</i>
	 */
	int K2616_SLE4442ReadSafety(HANDLE ComHandle, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_SLE4442Write(HANDLE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:173</i><br>
	 * @deprecated use the safer methods {@link #K2616_SLE4442Write(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, ByteBuffer)} and {@link #K2616_SLE4442Write(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_SLE4442Write(HANDLE ComHandle, byte _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_SLE4442Write(HANDLE, BYTE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:173</i>
	 */
	int K2616_SLE4442Write(HANDLE ComHandle, byte _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_SLE4442WriteProtectBit(HANDLE, BYTE, BYTE, BYTE[32])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:174</i><br>
	 * @deprecated use the safer methods {@link #K2616_SLE4442WriteProtectBit(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, ByteBuffer)} and {@link #K2616_SLE4442WriteProtectBit(k2616_dll.K2616_DllLibrary.HANDLE, byte, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_SLE4442WriteProtectBit(HANDLE ComHandle, byte _Address, byte _DataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_SLE4442WriteProtectBit(HANDLE, BYTE, BYTE, BYTE[32])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:174</i>
	 */
	int K2616_SLE4442WriteProtectBit(HANDLE ComHandle, byte _Address, byte _DataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_SLE4442ChangePWD(HANDLE, BYTE[3])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:175</i><br>
	 * @deprecated use the safer methods {@link #K2616_SLE4442ChangePWD(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_SLE4442ChangePWD(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_SLE4442ChangePWD(HANDLE ComHandle, Pointer _PWData);
	/**
	 * Original signature : <code>int K2616_SLE4442ChangePWD(HANDLE, BYTE[3])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:175</i>
	 */
	int K2616_SLE4442ChangePWD(HANDLE ComHandle, ByteBuffer _PWData);
	/**
	 * +++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_Sle4428Reset(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:177</i>
	 */
	int K2616_Sle4428Reset(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_Sle4428VerifyPWD(HANDLE, BYTE[2])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:178</i><br>
	 * @deprecated use the safer methods {@link #K2616_Sle4428VerifyPWD(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_Sle4428VerifyPWD(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_Sle4428VerifyPWD(HANDLE ComHandle, Pointer _PWData);
	/**
	 * Original signature : <code>int K2616_Sle4428VerifyPWD(HANDLE, BYTE[2])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:178</i>
	 */
	int K2616_Sle4428VerifyPWD(HANDLE ComHandle, ByteBuffer _PWData);
	/**
	 * Original signature : <code>int K2616_Sle4428Read(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:179</i><br>
	 * @deprecated use the safer methods {@link #K2616_Sle4428Read(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, ByteBuffer)} and {@link #K2616_Sle4428Read(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_Sle4428Read(HANDLE ComHandle, int _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_Sle4428Read(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:179</i>
	 */
	int K2616_Sle4428Read(HANDLE ComHandle, int _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_Sle4428ReadProtectBit(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:180</i><br>
	 * @deprecated use the safer methods {@link #K2616_Sle4428ReadProtectBit(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, ByteBuffer)} and {@link #K2616_Sle4428ReadProtectBit(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_Sle4428ReadProtectBit(HANDLE ComHandle, int _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_Sle4428ReadProtectBit(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:180</i>
	 */
	int K2616_Sle4428ReadProtectBit(HANDLE ComHandle, int _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_Sle4428Write(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:181</i><br>
	 * @deprecated use the safer methods {@link #K2616_Sle4428Write(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, ByteBuffer)} and {@link #K2616_Sle4428Write(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_Sle4428Write(HANDLE ComHandle, int _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_Sle4428Write(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:181</i>
	 */
	int K2616_Sle4428Write(HANDLE ComHandle, int _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_Sle4428WriteP(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:182</i><br>
	 * @deprecated use the safer methods {@link #K2616_Sle4428WriteP(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, ByteBuffer)} and {@link #K2616_Sle4428WriteP(k2616_dll.K2616_DllLibrary.HANDLE, int, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_Sle4428WriteP(HANDLE ComHandle, int _Address, byte _dataLen, Pointer _BlockData);
	/**
	 * Original signature : <code>int K2616_Sle4428WriteP(HANDLE, int, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:182</i>
	 */
	int K2616_Sle4428WriteP(HANDLE ComHandle, int _Address, byte _dataLen, ByteBuffer _BlockData);
	/**
	 * Original signature : <code>int K2616_Sle4428ChangePWD(HANDLE, BYTE[2])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:183</i><br>
	 * @deprecated use the safer methods {@link #K2616_Sle4428ChangePWD(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_Sle4428ChangePWD(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_Sle4428ChangePWD(HANDLE ComHandle, Pointer _PWData);
	/**
	 * Original signature : <code>int K2616_Sle4428ChangePWD(HANDLE, BYTE[2])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:183</i>
	 */
	int K2616_Sle4428ChangePWD(HANDLE ComHandle, ByteBuffer _PWData);
	/**
	 * ++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_CPUTypeACardPowerOn(HANDLE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:186</i><br>
	 * @deprecated use the safer methods {@link #K2616_CPUTypeACardPowerOn(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_CPUTypeACardPowerOn(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_CPUTypeACardPowerOn(HANDLE ComHandle, Pointer szATR);
	/**
	 * ++++++++++++++++++++++++++++++++++++++++++++++++++//<br>
	 * Original signature : <code>int K2616_CPUTypeACardPowerOn(HANDLE, BYTE[16])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:186</i>
	 */
	int K2616_CPUTypeACardPowerOn(HANDLE ComHandle, ByteBuffer szATR);
	/**
	 * Original signature : <code>int K2616_CPUTypeAAPDU(HANDLE, BYTE, int, BYTE[], BYTE*, BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:187</i><br>
	 * @deprecated use the safer methods {@link #K2616_CPUTypeAAPDU(k2616_dll.K2616_DllLibrary.HANDLE, byte, int, ByteBuffer, ByteBuffer, ByteBuffer, IntBuffer)} and {@link #K2616_CPUTypeAAPDU(k2616_dll.K2616_DllLibrary.HANDLE, byte, int, Pointer, Pointer, Pointer, IntByReference)} instead
	 */
	@Deprecated 
	int K2616_CPUTypeAAPDU(HANDLE ComHandle, byte SCH, int _dataLen, Pointer _APDUData, Pointer RCH, Pointer _exData, IntByReference _exdataLen);
	/**
	 * Original signature : <code>int K2616_CPUTypeAAPDU(HANDLE, BYTE, int, BYTE[], BYTE*, BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:187</i>
	 */
	int K2616_CPUTypeAAPDU(HANDLE ComHandle, byte SCH, int _dataLen, ByteBuffer _APDUData, ByteBuffer RCH, ByteBuffer _exData, IntBuffer _exdataLen);
	/**
	 * Original signature : <code>int K2616_GetMachineIDNum(HANDLE, BYTE*, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:188</i><br>
	 * @deprecated use the safer methods {@link #K2616_GetMachineIDNum(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer, ByteBuffer)} and {@link #K2616_GetMachineIDNum(k2616_dll.K2616_DllLibrary.HANDLE, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_GetMachineIDNum(HANDLE ComHandle, Pointer length, Pointer IDNum);
	/**
	 * Original signature : <code>int K2616_GetMachineIDNum(HANDLE, BYTE*, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:188</i>
	 */
	int K2616_GetMachineIDNum(HANDLE ComHandle, ByteBuffer length, ByteBuffer IDNum);
	/**
	 * Original signature : <code>int K2616_SetMachineIDNum(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:189</i><br>
	 * @deprecated use the safer methods {@link #K2616_SetMachineIDNum(k2616_dll.K2616_DllLibrary.HANDLE, byte, ByteBuffer)} and {@link #K2616_SetMachineIDNum(k2616_dll.K2616_DllLibrary.HANDLE, byte, Pointer)} instead
	 */
	@Deprecated 
	int K2616_SetMachineIDNum(HANDLE ComHandle, byte length, Pointer IDNum);
	/**
	 * Original signature : <code>int K2616_SetMachineIDNum(HANDLE, BYTE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:189</i>
	 */
	int K2616_SetMachineIDNum(HANDLE ComHandle, byte length, ByteBuffer IDNum);
	/**
	 * Original signature : <code>int K2616_TestCmd(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:190</i>
	 */
	int K2616_TestCmd(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_SendCard(HANDLE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:191</i>
	 */
	int K2616_SendCard(HANDLE ComHandle, byte _PM);
	/**
	 * Original signature : <code>int K2616_RecycleCard(HANDLE, BYTE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:192</i>
	 */
	int K2616_RecycleCard(HANDLE ComHandle, byte _PM);
	/**
	 * Original signature : <code>int K2616_SelectPSE(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:201</i>
	 */
	int K2616_SelectPSE(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_ReadPSEDirFile(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:202</i>
	 */
	int K2616_ReadPSEDirFile(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_SelectADFFile(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:203</i>
	 */
	int K2616_SelectADFFile(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_GPOCMD(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:204</i>
	 */
	int K2616_GPOCMD(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_ReadRecordFile(HANDLE, int*, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:205</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadRecordFile(k2616_dll.K2616_DllLibrary.HANDLE, IntBuffer, ByteBuffer)} and {@link #K2616_ReadRecordFile(k2616_dll.K2616_DllLibrary.HANDLE, IntByReference, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadRecordFile(HANDLE ComHandle, IntByReference len, Pointer CardID);
	/**
	 * Original signature : <code>int K2616_ReadRecordFile(HANDLE, int*, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:205</i>
	 */
	int K2616_ReadRecordFile(HANDLE ComHandle, IntBuffer len, ByteBuffer CardID);
	/**
	 * Original signature : <code>int K2616_ReadICCardNum(HANDLE, int*, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:206</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadICCardNum(k2616_dll.K2616_DllLibrary.HANDLE, IntBuffer, ByteBuffer)} and {@link #K2616_ReadICCardNum(k2616_dll.K2616_DllLibrary.HANDLE, IntByReference, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadICCardNum(HANDLE ComHandle, IntByReference len, Pointer CardID);
	/**
	 * Original signature : <code>int K2616_ReadICCardNum(HANDLE, int*, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:206</i>
	 */
	int K2616_ReadICCardNum(HANDLE ComHandle, IntBuffer len, ByteBuffer CardID);
	/**
	 * Original signature : <code>int K2616_CPUTypeASelectPSE(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:208</i>
	 */
	int K2616_CPUTypeASelectPSE(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_CPUTypeAReadPSEDirFile(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:209</i>
	 */
	int K2616_CPUTypeAReadPSEDirFile(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_CPUTypeASelectADFFile(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:210</i>
	 */
	int K2616_CPUTypeASelectADFFile(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_CPUTypeAGPOCMD(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:211</i>
	 */
	int K2616_CPUTypeAGPOCMD(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_CPUTypeAReadRecordFile(HANDLE, int*, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:212</i><br>
	 * @deprecated use the safer methods {@link #K2616_CPUTypeAReadRecordFile(k2616_dll.K2616_DllLibrary.HANDLE, IntBuffer, ByteBuffer)} and {@link #K2616_CPUTypeAReadRecordFile(k2616_dll.K2616_DllLibrary.HANDLE, IntByReference, Pointer)} instead
	 */
	@Deprecated 
	int K2616_CPUTypeAReadRecordFile(HANDLE ComHandle, IntByReference len, Pointer CardID);
	/**
	 * Original signature : <code>int K2616_CPUTypeAReadRecordFile(HANDLE, int*, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:212</i>
	 */
	int K2616_CPUTypeAReadRecordFile(HANDLE ComHandle, IntBuffer len, ByteBuffer CardID);
	/**
	 * Original signature : <code>int K2616_CPUTypeAReadICCardNum(HANDLE, int*, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:213</i><br>
	 * @deprecated use the safer methods {@link #K2616_CPUTypeAReadICCardNum(k2616_dll.K2616_DllLibrary.HANDLE, IntBuffer, ByteBuffer)} and {@link #K2616_CPUTypeAReadICCardNum(k2616_dll.K2616_DllLibrary.HANDLE, IntByReference, Pointer)} instead
	 */
	@Deprecated 
	int K2616_CPUTypeAReadICCardNum(HANDLE ComHandle, IntByReference len, Pointer CardID);
	/**
	 * Original signature : <code>int K2616_CPUTypeAReadICCardNum(HANDLE, int*, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:213</i>
	 */
	int K2616_CPUTypeAReadICCardNum(HANDLE ComHandle, IntBuffer len, ByteBuffer CardID);
	/**
	 * Original signature : <code>int K2616_ReadRetainCount(HANDLE, int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:215</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadRetainCount(k2616_dll.K2616_DllLibrary.HANDLE, IntBuffer)} and {@link #K2616_ReadRetainCount(k2616_dll.K2616_DllLibrary.HANDLE, IntByReference)} instead
	 */
	@Deprecated 
	int K2616_ReadRetainCount(HANDLE ComHandle, IntByReference Count);
	/**
	 * Original signature : <code>int K2616_ReadRetainCount(HANDLE, int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:215</i>
	 */
	int K2616_ReadRetainCount(HANDLE ComHandle, IntBuffer Count);
	/**
	 * Original signature : <code>int K2616_ClearRetainCount(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:216</i>
	 */
	int K2616_ClearRetainCount(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_SelectSocialSecurityApp(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:218</i>
	 */
	int K2616_SelectSocialSecurityApp(HANDLE ComHandle);
	/**
	 * Original signature : <code>int K2616_SelectSocialSecurityBasicFile(HANDLE)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:219</i>
	 */
	int K2616_SelectSocialSecurityBasicFile(HANDLE ComHandle);
	/**
	 * int __stdcall K2616_LNSelectSocialSecurityDataFile(HANDLE ComHandle);<br>
	 * Original signature : <code>int K2616_ReadSocialSecurityCardID(HANDLE, BYTE[9])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:222</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadSocialSecurityCardID(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_ReadSocialSecurityCardID(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadSocialSecurityCardID(HANDLE ComHandle, Pointer IDNum);
	/**
	 * int __stdcall K2616_LNSelectSocialSecurityDataFile(HANDLE ComHandle);<br>
	 * Original signature : <code>int K2616_ReadSocialSecurityCardID(HANDLE, BYTE[9])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:222</i>
	 */
	int K2616_ReadSocialSecurityCardID(HANDLE ComHandle, ByteBuffer IDNum);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityIDNum(HANDLE, BYTE[18])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:223</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadSocialSecurityIDNum(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_ReadSocialSecurityIDNum(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadSocialSecurityIDNum(HANDLE ComHandle, Pointer IDNum);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityIDNum(HANDLE, BYTE[18])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:223</i>
	 */
	int K2616_ReadSocialSecurityIDNum(HANDLE ComHandle, ByteBuffer IDNum);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityName(HANDLE, BYTE[30])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:224</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadSocialSecurityName(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_ReadSocialSecurityName(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadSocialSecurityName(HANDLE ComHandle, Pointer Name);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityName(HANDLE, BYTE[30])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:224</i>
	 */
	int K2616_ReadSocialSecurityName(HANDLE ComHandle, ByteBuffer Name);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityGender(HANDLE, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:225</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadSocialSecurityGender(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_ReadSocialSecurityGender(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadSocialSecurityGender(HANDLE ComHandle, Pointer Sex);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityGender(HANDLE, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:225</i>
	 */
	int K2616_ReadSocialSecurityGender(HANDLE ComHandle, ByteBuffer Sex);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityNation(HANDLE, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:226</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadSocialSecurityNation(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_ReadSocialSecurityNation(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadSocialSecurityNation(HANDLE ComHandle, Pointer Nation);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityNation(HANDLE, BYTE*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:226</i>
	 */
	int K2616_ReadSocialSecurityNation(HANDLE ComHandle, ByteBuffer Nation);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityRegional(HANDLE, BYTE[3])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:227</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadSocialSecurityRegional(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_ReadSocialSecurityRegional(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadSocialSecurityRegional(HANDLE ComHandle, Pointer Regional);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityRegional(HANDLE, BYTE[3])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:227</i>
	 */
	int K2616_ReadSocialSecurityRegional(HANDLE ComHandle, ByteBuffer Regional);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityBirthDay(HANDLE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:228</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadSocialSecurityBirthDay(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_ReadSocialSecurityBirthDay(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadSocialSecurityBirthDay(HANDLE ComHandle, Pointer BirthDay);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityBirthDay(HANDLE, BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:228</i>
	 */
	int K2616_ReadSocialSecurityBirthDay(HANDLE ComHandle, ByteBuffer BirthDay);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityInfo(HANDLE, BYTE[18], BYTE[30], BYTE*, BYTE*, BYTE[3], BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:229</i><br>
	 * @deprecated use the safer methods {@link #K2616_ReadSocialSecurityInfo(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer)} and {@link #K2616_ReadSocialSecurityInfo(k2616_dll.K2616_DllLibrary.HANDLE, Pointer, Pointer, Pointer, Pointer, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_ReadSocialSecurityInfo(HANDLE ComHandle, Pointer IDNum, Pointer Name, Pointer Sex, Pointer Nation, Pointer Regional, Pointer BirthDay);
	/**
	 * Original signature : <code>int K2616_ReadSocialSecurityInfo(HANDLE, BYTE[18], BYTE[30], BYTE*, BYTE*, BYTE[3], BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:229</i>
	 */
	int K2616_ReadSocialSecurityInfo(HANDLE ComHandle, ByteBuffer IDNum, ByteBuffer Name, ByteBuffer Sex, ByteBuffer Nation, ByteBuffer Regional, ByteBuffer BirthDay);
	/**
	 * Original signature : <code>int K2616_AutoReadSocialSecurityInfo(HANDLE, BYTE[18], BYTE[30], BYTE*, BYTE*, BYTE[3], BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:230</i><br>
	 * @deprecated use the safer methods {@link #K2616_AutoReadSocialSecurityInfo(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer)} and {@link #K2616_AutoReadSocialSecurityInfo(k2616_dll.K2616_DllLibrary.HANDLE, Pointer, Pointer, Pointer, Pointer, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AutoReadSocialSecurityInfo(HANDLE ComHandle, Pointer IDNum, Pointer Name, Pointer Sex, Pointer Nation, Pointer Regional, Pointer BirthDay);
	/**
	 * Original signature : <code>int K2616_AutoReadSocialSecurityInfo(HANDLE, BYTE[18], BYTE[30], BYTE*, BYTE*, BYTE[3], BYTE[4])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:230</i>
	 */
	int K2616_AutoReadSocialSecurityInfo(HANDLE ComHandle, ByteBuffer IDNum, ByteBuffer Name, ByteBuffer Sex, ByteBuffer Nation, ByteBuffer Regional, ByteBuffer BirthDay);
	/**
	 * Original signature : <code>int K2616_AutoReadSocialSecurityCardID(HANDLE, BYTE[9])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:231</i><br>
	 * @deprecated use the safer methods {@link #K2616_AutoReadSocialSecurityCardID(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_AutoReadSocialSecurityCardID(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AutoReadSocialSecurityCardID(HANDLE ComHandle, Pointer CardID);
	/**
	 * Original signature : <code>int K2616_AutoReadSocialSecurityCardID(HANDLE, BYTE[9])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:231</i>
	 */
	int K2616_AutoReadSocialSecurityCardID(HANDLE ComHandle, ByteBuffer CardID);
	/**
	 * Original signature : <code>int K2616_AutoReadSocialSecurityInfoAndCardID(HANDLE, BYTE[18], BYTE[30], BYTE*, BYTE*, BYTE[3], BYTE[4], BYTE[9])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:232</i><br>
	 * @deprecated use the safer methods {@link #K2616_AutoReadSocialSecurityInfoAndCardID(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer, ByteBuffer)} and {@link #K2616_AutoReadSocialSecurityInfoAndCardID(k2616_dll.K2616_DllLibrary.HANDLE, Pointer, Pointer, Pointer, Pointer, Pointer, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int K2616_AutoReadSocialSecurityInfoAndCardID(HANDLE ComHandle, Pointer IDNum, Pointer Name, Pointer Sex, Pointer Nation, Pointer Regional, Pointer BirthDay, Pointer CardID);
	/**
	 * Original signature : <code>int K2616_AutoReadSocialSecurityInfoAndCardID(HANDLE, BYTE[18], BYTE[30], BYTE*, BYTE*, BYTE[3], BYTE[4], BYTE[9])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:232</i>
	 */
	int K2616_AutoReadSocialSecurityInfoAndCardID(HANDLE ComHandle, ByteBuffer IDNum, ByteBuffer Name, ByteBuffer Sex, ByteBuffer Nation, ByteBuffer Regional, ByteBuffer BirthDay, ByteBuffer CardID);
	/**
	 * Original signature : <code>int K2616_CPUTypeBCardPowerOn(HANDLE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:233</i><br>
	 * @deprecated use the safer methods {@link #K2616_CPUTypeBCardPowerOn(k2616_dll.K2616_DllLibrary.HANDLE, ByteBuffer)} and {@link #K2616_CPUTypeBCardPowerOn(k2616_dll.K2616_DllLibrary.HANDLE, Pointer)} instead
	 */
	@Deprecated 
	int K2616_CPUTypeBCardPowerOn(HANDLE ComHandle, Pointer szATR);
	/**
	 * Original signature : <code>int K2616_CPUTypeBCardPowerOn(HANDLE, BYTE[])</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:233</i>
	 */
	int K2616_CPUTypeBCardPowerOn(HANDLE ComHandle, ByteBuffer szATR);
	/**
	 * Original signature : <code>int K2616_CPUTypeBAPDU(HANDLE, BYTE, int, BYTE[], BYTE*, BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:234</i><br>
	 * @deprecated use the safer methods {@link #K2616_CPUTypeBAPDU(k2616_dll.K2616_DllLibrary.HANDLE, byte, int, ByteBuffer, ByteBuffer, ByteBuffer, IntBuffer)} and {@link #K2616_CPUTypeBAPDU(k2616_dll.K2616_DllLibrary.HANDLE, byte, int, Pointer, Pointer, Pointer, IntByReference)} instead
	 */
	@Deprecated 
	int K2616_CPUTypeBAPDU(HANDLE ComHandle, byte SCH, int _dataLen, Pointer _APDUData, Pointer RCH, Pointer _exData, IntByReference _exdataLen);
	/**
	 * Original signature : <code>int K2616_CPUTypeBAPDU(HANDLE, BYTE, int, BYTE[], BYTE*, BYTE[], int*)</code><br>
	 * <i>native declaration : drivers\card\K2616_Dll.h:234</i>
	 */
	int K2616_CPUTypeBAPDU(HANDLE ComHandle, byte SCH, int _dataLen, ByteBuffer _APDUData, ByteBuffer RCH, ByteBuffer _exData, IntBuffer _exdataLen);
	public static class HANDLE extends PointerType {
		public HANDLE(Pointer address) {
			super(address);
		}
		public HANDLE() {
			super();
		}
	};
}
